title: Chandana Nawarathna - Building Scalable Digital Solutions
description: "Discover how Chandana Nawarathna helps businesses grow with scalable digital solutions in cloud computing, DevOps, and software development."
author:
  name: "Chandana Nawarathna"
  email: "cnawarathna@gmail.com"
  url: "https://chandanadev.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 15
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Chandana Nawarathna"
year : "2025"
